export const chars = [
  {sound: "e", write:"e", display: "i"},
  {sound: "i̱", write: "E", display: "i̱"},
  {sound: "i", write: "i", display: "i"},
  {sound: "u", write: "u", display: "o"},
  {sound: "o", write: "o", display: "o"},
  {sound: "o̱", write: "O", display: "o̱"},
  {sound: "a", write: "a", display: "a"},
  {sound: "a̱", write: "A", display: "a̱"},
  {sound: "p", write: "p", display: "p"},
  {sound: "b", write: "b", display: "b"},
  {sound: "m", write: "m", display: "m"},
  {sound: "t", write: "t", display: "t"},
  {sound: "n", write: "n", display: "n"},
  {sound: "k", write: "k", display: "k"},
  {sound: "ng", write: "N", display: "ng"},
  {sound: "h", write: "h", display: "h"},
  {sound: "w", write: "w", display: "w"},
  {sound: "f", write: "f", display: "f"},
  {sound: "ch", write: "C", display: "ch"},
  {sound: "l", write: "l", display: "l"},
  {sound: "lh", write: "L", display: "lh"},
  {sound: "y", write: "y", display: "y"},
  {sound: "s", write: "s", display: "s"},
  {sound: "sh", write: "S", display: "sh"},
  {sound: "'", write: "G", display: "' Glottal stop"}
];
